import { StyleSheet } from 'react-native';

export const HarmonyButtonStyle = StyleSheet.create({
    //TODO: ADD STYLES HERE
    container:{
        width: '100%', 
        display : 'flex',
        alignItems : 'center'   
    },

    primary:{
        color: 'white',
    },
    secondary:{
        color: 'black',
    },
    subtle:{
        color: 'black',
    },
    text:{
        color: 'black',
    },
    initial:{
        borderRadius: 10,
        backgroundColor:'#394867',
        height:64,
        width:200,
        color: '#ffffff',
        fontFamily: "SFProDisplay-Regular",
        fontStyle: 'normal',
        fontWeight: "600",
        fontSize: 16,
        lineHeight: 28,
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        letterSpacing: 0.75,

    },
    active:{
        borderRadius: 10,
        backgroundColor:'#394867',
        height:64,
        width:200,
        fontStyle: 'normal',
        fontWeight: "600",
        fontSize: 16,
        lineHeight: 28,
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        letterSpacing: 0.75,
    },
    loading:{
        borderRadius: 10,
        backgroundColor:'#394867',
        height:64,
        width:200,
        color: '#ffffff',
        fontStyle: 'normal',
        fontWeight: "600",
        fontSize: 16,
        lineHeight: 28,
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        letterSpacing: 0.75,
    },
    spinnerTextStyle: {
        color: '#FFF'
      },
    disabled:{
        borderRadius: 10,
        backgroundColor:'#394867',
        height:64,
        width:200,
        opacity: 0.5,
        color: '#ffffff',
        fontStyle: 'normal',
        fontSize: 16,
        fontWeight: "600",
        lineHeight: 28,
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        letterSpacing: 0.75,
    },
    secinitial:{
        borderRadius: 10,
        backgroundColor:'#ffffff',
        borderWidth: 2,
        borderColor:'#394867',
        height:64,
        width:200,
        // color: '#ffffff',
        fontStyle: 'normal',
        fontWeight: "600",
        fontSize: 16,
        lineHeight: 28,
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        letterSpacing: 0.75,
    },
    secActive:{
        borderRadius: 10,
        backgroundColor:'#ffffff',
        borderWidth: 2,
        borderColor:'#394867',
        height:64,
        width:200,
        fontStyle: 'normal',
        fontWeight: "600",
        fontSize: 16,
        lineHeight: 28,
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        letterSpacing: 0.75,
    },
    secLoading:{
        borderRadius: 10,
        backgroundColor:'#ffffff',
        borderWidth: 2,
        borderColor:'#394867',
        height:64,
        width:200,
        
        fontStyle: 'normal',
        fontWeight: "600",
        fontSize: 16,
        lineHeight: 28,
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        letterSpacing: 0.75,
    },
    secDisabled:{
        borderRadius: 10,
        backgroundColor:'#ffffff',
        borderWidth: 2,
        borderColor:'#394867',
        opacity: 0.5,
        height:64,
        width:200,
        color: 'red',
        fontStyle: 'normal',
        fontWeight: "600",
        fontSize: 16,
        lineHeight: 28,
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        letterSpacing: 0.75
    },
    subinitial:{
        borderRadius: 10,
        
        borderWidth: 2,
        borderColor:'#D6D8E7',
        height:64,
        width:200,
        // color: '#ffffff',
        fontStyle: 'normal',
        fontWeight: "600",
        fontSize: 16,
        lineHeight: 28,
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        letterSpacing: 0.75,
    },
    subActive:{
        borderRadius: 10,
        
        borderWidth: 2,
        borderColor:'#D6D8E7',
        height:64,
        width:200,
        fontStyle: 'normal',
        fontWeight: "600",
        fontSize: 16,
        lineHeight: 28,
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        letterSpacing: 0.75,
    },
    subLoading:{
        borderRadius: 10,
        
        borderWidth: 2,
        borderColor:'#394867',
        height:64,
        width:200,
        
        fontStyle: 'normal',
        fontWeight: "600",
        fontSize: 16,
        lineHeight: 28,
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        letterSpacing: 0.75,
    },
    subDisabled:{
        borderRadius: 10,
        
        borderWidth: 2,
        borderColor:'#D6D8E7',
        opacity: 0.5,
        height:64,
        width:200,
        color: 'red',
        fontStyle: 'normal',
        fontWeight: "600",
        fontSize: 16,
        lineHeight: 28,
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        letterSpacing: 0.75,

    },
    textInitial:{
        borderRadius: 40,
        
       
        
        height:64,
        width:200,
        // color: '#ffffff',
        fontStyle: 'normal',
        fontWeight: "600",
        fontSize: 16,
        lineHeight: 28,
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        letterSpacing: 0.75,
    },
    textActive:{
        borderRadius: 10,
        
       
        
        height:64,
        width:200,
        fontStyle: 'normal',
        fontWeight: "600",
        fontSize: 16,
        lineHeight: 28,
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        letterSpacing: 0.75,
    },
    textLoading:{
        borderRadius: 40,
        
       
        height:64,
        width:200,
        
        fontStyle: 'normal',
        fontWeight: "600",
        fontSize: 16,
        lineHeight: 28,
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        letterSpacing: 0.75,
    },
    textDisabled:{
        borderRadius: 40,
        
        
        
        opacity: 0.5,
        height:64,
        width:200,
        color: 'red',
        fontStyle: 'normal',
        fontWeight: "600",
        fontSize: 16,
        lineHeight: 28,
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        justifyContent: 'center',
        letterSpacing: 0.75,

    },
    

     
})
